### ISSUE TITLE
Make pairs and straights discardable

### ISSUE THREAD

**Issue by donEnno** [donEnno/janosch#1]

**Comment by donEnno** [comment]
Works except that 

- first round into pairs yields wrong available cards (unsure)
- straights might not work when a Joker is included

**Comment by leuschjanphilipp** [comment]
```
Enno - Hand: [2C, 8H, 9D, 9S, 10D], Score: 0
Janosch? Type y if so, else type any button
Enter indices of the cards to discard (like 1 2 3): 2 3 4 5
Invalid move.
  0%|                                                                                                                                                                                                                                                    | 0/1 [06:21<?, ?it/s] 
Traceback (most recent call last):
  File "E:\Projects\Janosh_game\janosch\play_janosch.py", line 35, in <module>
    main(args.rounds, args.silent)
  File "E:\Projects\Janosh_game\janosch\play_janosch.py", line 23, in main
    loser = game.start_game()
            ^^^^^^^^^^^^^^^^^
  File "E:\Projects\Janosh_game\janosch\janosch.py", line 268, in start_game
    self.play_turn(self.current_player_index)
  File "E:\Projects\Janosh_game\janosch\janosch.py", line 123, in play_turn
    self.draw_card_action(player)
  File "E:\Projects\Janosh_game\janosch\janosch.py", line 202, in draw_card_action
    player.add_card(drawn_card)
                    ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'drawn_card' where it is not associated with a value
```
